# base image  
FROM python:3.11 

# set environment variables  
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  

# install dependencies  
RUN pip install --upgrade pip  

# copy whole project to docker directory. 
COPY . .

# run this command to install all dependencies  
RUN pip install --no-cache-dir -r requirements.txt  

# port where the Django app runs  
EXPOSE 8000  

# start server  
RUN python manage.py makemigrations
RUN python manage.py migrate
CMD python manage.py runserver  