# Generated by Django 5.0.3 on 2024-03-15 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_cards', models.CharField(default='', max_length=10)),
                ('player_to_play', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('blind', models.IntegerField(default=25)),
                ('min_raise', models.IntegerField(default=25)),
                ('winners_name', models.CharField(default='', max_length=1500)),
                ('winner_hand', models.CharField(default='', max_length=50)),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
